### ISSUE TITLE
How to use electron with esri api?

### ISSUE THREAD

**Issue by flytam** [kgs916/ng-cli-electron-esri#1]
I meet the error "path must be a string " when useing electron+react+esri , How can I deal with it?I have seen u ask the same question on the github. Thanks

**Comment by TheKeithStewart** [comment]
This is being discussed at https://github.com/tomwayson/esri-loader/issues/21.  I believe we are close to a resolution.

**Comment by flytam** [comment]
@kgs916 Have u solve the problem?

**Comment by TheKeithStewart** [comment]
We've identified the issue and there is a pull request pending (https://github.com/tomwayson/esri-loader/pull/22) that will solve the issue in the esri-loader. Once the PR has been merged I will be updating this example.

**Comment by flytam** [comment]
@kgs916 @kgs916  thank you so much.I have solve the problem with your suggestion. But i meet a new problem now,when i link the arcGis's css from the cdn in the html
```
<link rel="stylesheet" href="https://js.arcgis.com/4.3/esri/css/main.css">
```
The map wont appear,but with no error in the console.When i delete the link tags on the developTools ,the map will appear or  the map will appear normally if  i make the  arcGis css lazy load(use setTimeout to create the link)  .I feel confused. Have u meet the problem?

**Comment by TheKeithStewart** [comment]
@Tanjh1996 no, I haven't experienced this before.  In many of the apps that I've worked on the css is being imported in one of the component styles files like this:

```
@import 'https://js.arcgis.com/4.3/esri/css/main.css';
```

The css seems to work just fine when imported like this.

**Comment by Tanjh1996** [comment]
@kgs916  i have check this method but it has the same problem. or i give my code you and test it?

**Comment by TheKeithStewart** [comment]
@Tanjh1996 If you post an example someplace I can take a look and see if anything jumps out at me

**Comment by flytam** [comment]
@kgs916 Thanks,i have solved the error. It is the reason that i place the link tag on the error place which has a conflict with webpack's output css.
